### ISSUE TITLE
Topic for ILUGD Talk on 06-May-2017

### ISSUE THREAD

**Issue by hiharcharan** [ILUGD/ILUGD.github.io#12]
I was thinking of delivering a talk on simple but following powerful tools - 
* filters, sed and awk (45mins) 
* talking to the shell, shell scripting tidbits (30mins)
Will take one topic this time, the other one next time. Or if you folks are OK, then both topics.

**Comment by sourabhtk37** [comment]
Hey @hiharcharan Not here.
Propose your talk [here](https://github.com/ILUGD/talks/issues). Preferably with [this](https://github.com/ilUGD/talks/issues/13) format.
