### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by realslimshanky** [ILUGD/ILUGD.github.io#2]
Attaching some wireframe ideas to work on

[For Desktop](https://www.figma.com/file/Q0e8utx7nn56iOBSNwwvZaiE/ILUG-D)
[For Mobile](https://www.figma.com/file/RLEBE1JdQLJ7v39DbhyY1aSo/ILUG-D-Mobile)

**Comment by thisisayush** [comment]
Check out PR #8 if it suits the desktop specifications :)
