### ISSUE TITLE
linuxdelhi.org does not resolve

### ISSUE THREAD

**Issue by manasb** [ILUGD/ILUGD.github.io#22]
Just tried to access ilugd.github.io, got redirected to linuxdelhi.org which did not resolve.

**Comment by rajudev** [comment]
the url-name specified is wrong as I can see. 
linuxdelhi.org is given in CNAME, it should be linux-delhi.org

**Comment by manasb** [comment]
I see the site now!

Thank you @rajudev

**Comment by rajudev** [comment]
linuxdelhi.org is indeed our domain registered with triveni. I have stopped the redirection for the time being the redirections are figured out properly.
