### ISSUE TITLE
Open a memes section 

### ISSUE THREAD

**Issue by hellozee** [ILUGD/ILUGD.github.io#42]
For more info take a look [here](https://t.me/ilugdmemes)

**Comment by rajudev** [comment]
when can we get this done?

**Comment by MetalDent** [comment]
Hi!
You want random memes generated? For that you can use an API. 
Or your custom memes?

**Comment by ajax711** [comment]
@MetalDent Not exactly. Some of us created some fun memes on community members and wanted to make a memes section to host them. Am I getting it right @hellozee

**Comment by hellozee** [comment]
@ajax711 yes,  @MetalDent we already have a memes channel in Telegram, we need a simple grid view showcasing all the memes, probably something like Pinterest's feed

**Comment by xeon-zolt** [comment]
@hellozee can you DM me some of the approved memes? which can be posted on web also can you tell under which section should meme come? community activity can be a new tab where a new timeline feature can also be added

**Comment by hellozee** [comment]
@xeon-zolt I think you can pick some popular ones are post it to the website
