### ISSUE TITLE
Tech talk proposal  Programing Microcontrollers -The embedded world

### ISSUE THREAD

**Issue by vikrantdeveloper** [ILUGD/ILUGD.github.io#55]
Attaching my tech talk proposal ->Programing microcontrollers-- The embedded world
[Hardware Hackers TECH Talk proposal.pdf](https://github.com/ILUGD/ILUGD.github.io/files/3517529/Hardware.Hackers.TECH.Talk.proposal.pdf)

**Comment by miphilomath** [comment]
Thank you the talk proposal

Closing the issue as this is the repository for the talk. The repository you are looking for is "[talks](https://github.com/ilugd/talks/issues)". Please create the issue again with your availability and share it on our telegram channel or mailing list.
