### ISSUE TITLE
Suggest what needs to be updated on our website

### ISSUE THREAD

**Issue by miphilomath** [ILUGD/ILUGD.github.io#61]
If you feel that our website lacks some information or any section that we should have on our website, please comment your suggestions on this issue and we will improve our website.

**Comment by miphilomath** [comment]
Listing all the suggestions we have so far:

#42 : Meme section
#57 : Highlight section for big events
#53 : Volunteers section

**Comment by insaaniManav** [comment]
condensed MOMs for all meetings

**Comment by miphilomath** [comment]
Add, how to contribute to the community section! (We need to decide on how part, blogs, tutorials etc)
